### ISSUE TITLE
composer request

### ISSUE THREAD

**Issue by ibourgeois** [thelia-modules/BrandCarousel#1]
Hello,

I am writing you to ask if we can use the devoption namespace on https://packagist.org/packages/devoption/

We noticed that this is the only repo you have in this namespace and it has been inactive for 3 years.

We are active contributers to the Laravel/PHP community and owners of the domain DevOption.io (site is not yet up, but coming soon) and the GitHub Organization https://github.com/devoption

We are attempting to release a laravel package that can deploy docker development environments for Laravel, but unable to use this namespace. 

Thank you for your time and consideration!

**Comment by mcaquet** [comment]
HelloYes you'll be able to use this namespace.Let me know what do you need me to do.RegardsMathias-------- Message original --------Objet : [thelia-modules/BrandCarousel] composer request (#1)De : Derek Bourgeois À : thelia-modules/BrandCarousel Cc : Subscribed Hello,
I am writing you to ask if we can use the devoption namespace on https://packagist.org/packages/devoption/
We noticed that this is the only repo you have in this namespace and it has been inactive for 3 years.
We are active contributers to the Laravel/PHP community and owners of the domain DevOption.io (site is not yet up, but coming soon) and the GitHub Organization https://github.com/devoption
We are attempting to release a laravel package that can deploy docker development environments for Laravel, but unable to use this namespace.
Thank you for your time and consideration!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thelia-modules/BrandCarousel","title":"thelia-modules/BrandCarousel","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thelia-modules/BrandCarousel"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"composer request (#1)"}],"action":{"name":"View Issue","url":"https://github.com/thelia-modules/BrandCarousel/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thelia-modules/BrandCarousel/issues/1",
"url": "https://github.com/thelia-modules/BrandCarousel/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "composer request (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Derek Bourgeois**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ibourgeois",
"facts": [
{
"name": "Repository: ",
"value": "thelia-modules/BrandCarousel"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thelia-modules/BrandCarousel\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thelia-modules/BrandCarousel\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thelia-modules/BrandCarousel/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 362097506\n}"
}
],
"themeColor": "26292E"
}
]
